#!/usr/bin/env ruby
require 'csv'
require 'json'


CODIGO_IBGE_MESOREGIOES = Hash[CSV.read('data/municipios_rs.csv').to_a[1..-1].map { |x| x[0..-3] }]
MESOREGIOES = {
  4301 => "Noroeste Rio-Grandense",
  4302 => "Nordeste Rio-Grandense",
  4303 => "Centro Ocidental Rio-Grandense",
  4304 => "Centro Oriental Rio-Grandense",
  4305 => "Metropolitana de Porto Alegre",
  4306 => "Sudoeste Rio-Grandense",
  4307 => "Sudeste Rio-Grandense"
}
CODIGO_IBGE_MICROREGIOES = Hash[CSV.read('data/municipios_rs.csv').to_a[1..-1].map { |x| [x[0], x[2]] }]
MICROREGIOES = {
  43001 => "SANTA ROSA", 43002 => "TRES PASSOS", 43003 => "FREDERICO WESTPHALEN", 43004 => "ERECHIM",
  43005 => "SANANDUVA", 43006 => "CERRO LARGO", 43007 => "SANTO ANGELO", 43008 => "IJUI", 43009 => "CARAZINHO",
  43010 => "PASSO FUNDO", 43011 => "CRUZ ALTA", 43012 => "NAO-ME-TOQUE", 43013 => "SOLEDADE", 43014 => "GUAPORE",
  43015 => "VACARIA", 43016 => "CAXIAS DO SUL", 43017 => "SANTIAGO", 43018 => "SANTA MARIA", 43019 => "RESTINGA SECA",
  43020 => "SANTA CRUZ DO SUL", 43021 => "LAJEADO-ESTRELA", 43022 => "CACHOEIRA DO SUL", 43023 => "MONTENEGRO",
  43024 => "GRAMADO-CANELA", 43025 => "SAO JERONIMO", 43026 => "PORTO ALEGRE", 43027 => "OSORIO", 43028 => "CAMAQUA",
  43029 => "CAMPANHA OCIDENTAL", 43030 => "CAMPANHA CENTRAL", 43031 => "CAMPANHA MERIDIONAL", 43032 => "SERRAS DE SUDESTE",
  43033 => "PELOTAS", 43034 => "JAGUARAO", 43035 => "LITORAL LAGUNAR"
}
ESTUPROS = CSV.read('data/estupros_mulheres_dados_abertos.csv', :col_sep => ';')[1..-1]
POPULACAO = CSV.read('data/populacao.csv', :col_sep => ',')[1..-1]

pop_por_regiao = {}
POPULACAO.each do |pop| 
  codigo = CODIGO_IBGE_MESOREGIOES[pop.first]
  pop_por_regiao[codigo] ||= 0
  pop_por_regiao[codigo] += pop.last.to_i

  codigo = CODIGO_IBGE_MICROREGIOES[pop.first]
  pop_por_regiao[codigo] ||= 0
  pop_por_regiao[codigo] += pop.last.to_i
end

results = {}
dias_da_semana = {}
dias_do_mes = {}
meses = {}
anos = {}

ESTUPROS.each do |estupro|
  municipio, ano, mes, dia, dia_da_semana, turno, hora, consumado, local, idade_vitima, idade_autor = *estupro

  next if (idade_vitima.to_i.zero? || idade_autor.to_i.zero?)

  municipio = $1 if municipio =~ /\((.*)\)/
  consumado = (consumado == 'Consumado')
  pela_manha = (turno =~ /(Manh|Tarde)/)

  populacao = 0
  POPULACAO.each do |pop|
    if pop.first == municipio
      populacao = pop.last
    end
  end

  anos[ano] = (anos[ano] || 0) + 1
  dias_da_semana[dia_da_semana] = (dias_da_semana[dia_da_semana] || 0) + 1
  meses[mes] = (meses[mes] || 0) + 1
  dias_do_mes[dia] = (dias_do_mes[dia] || 0) + 1


  dados = { :municipio => municipio, 
            :turno => turno,
            :local => local,
            :consumado => consumado,
            :idade_vitima => idade_vitima.to_i,
            :idade_autor => idade_autor.to_i,
            :pela_manha => pela_manha,
            :populacao => populacao.to_i }

  codigo_mesoregiao = CODIGO_IBGE_MESOREGIOES[municipio]
  results[codigo_mesoregiao] ||= []
  results[codigo_mesoregiao] << dados

  codigo_microregiao = CODIGO_IBGE_MICROREGIOES[municipio]
  results[codigo_microregiao] ||= []
  results[codigo_microregiao] << dados
end


resultado = {}
results.each_pair do |codigo, estupros|
  media_idade_vitima = estupros.map { |estupro| estupro[:idade_vitima] }.inject(:+) / estupros.length
  media_idade_autor = estupros.map { |estupro| estupro[:idade_autor] }.inject(:+) / estupros.length
  consumados = estupros.select { |estupro| estupro[:consumado] }.length
  pela_manha = estupros.select { |estupro| estupro[:pela_manha] }.length

  resultado[codigo] = { :nome => MESOREGIOES[codigo.to_i] || MICROREGIOES[codigo.to_i],
                        :media_idade_vitima => media_idade_vitima,
                        :media_idade_autor => media_idade_autor,
                        :consumado => consumados,
                        :pela_manha => pela_manha,
                        :ocorrencias => estupros.length,
                        :populacao => pop_por_regiao[codigo] }
end

resultado['anos'] = anos
resultado['meses'] = meses
resultado['dias_do_mes'] = dias_do_mes
resultado["dias_da_semana"] = dias_da_semana

File.open("data/dados_estupros.json","w") do |f|
  f.write(resultado.to_json)
end

